[toolchain]
anchor_version = "0.31.1"

[features]
seeds = true
skip-lint = false

[programs.localnet]
reit_rent = "8GKoDJSNEDbYWy1iF6Lewr8L3G9uuYSqqutB18QFC4Rw" //TODO

[programs.devnet]
reit_rent = "8GKoDJSNEDbYWy1iF6Lewr8L3G9uuYSqqutB18QFC4Rw" //TODO

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "Devnet"     # или "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
build = "anchor build"
deploy = "anchor deploy"
test = "anchor test"
